Members/urls.py
from django.urls import path

from . import views


app_name ='Members'
urlpatterns = [
    #member views
    path('', views.member_list,name ='member_list'),
    path('<int:id>/',views.member_details, name ='member_details'),
]

MyChama/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('Members.urls', namespace ='members')),
]

Loans/models.py
from django.db import models


class Loan(models.Model):
    LOAN_STATUS_CHOICES = [
        (0, 'Pending'),
        (1, 'Approved'),
        (2, 'Rejected'),
    ]
    REPAID_CHOICES = [
        (0, 'Yes'),
        (1, 'No'),
    ]

    member_id = models.IntegerField()
    ref_no = models.CharField(max_length=20,default="Unspecified")
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2)
    amount_due = models.DecimalField(max_digits=10, decimal_places=2, default= 0.00)
    interest = models.DecimalField(max_digits=10, decimal_places=2, default= 0.00)
    repaid_amount = models.DecimalField(max_digits=10, decimal_places=2, default= 0.00)
    loan_balance = models.DecimalField(max_digits=10, decimal_places=2, default= 0.00)
    loan_date = models.DateField()
    due_date = models.DateField()
    status = models.IntegerField(choices=LOAN_STATUS_CHOICES)
    comments = models.CharField(max_length=255,default="Unspecified")
    repaid = models.IntegerField(choices=REPAID_CHOICES, default=1)

Members/models.py
from django.db import models


ACTIVE_STATUS_CHOICES = [
        (0, 'Yes'),
        (1, 'No'),    
    ]

IS_STAFF_CHOICES = [
        (0, 'Yes'),
        (1, 'No'),    
    ]

ACC_TYPE_CHOICES = [
        (0, 'Business'),
        (1, 'Member'),    
    ]

class Member(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    id_no = models.IntegerField(default=0)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, unique=True)
    profession = models.CharField(max_length=50,default="Unspecified")
    joining_date = models.DateField()
    is_active = models.IntegerField(choices=ACTIVE_STATUS_CHOICES, default=0)
    is_staff = models.IntegerField(choices=IS_STAFF_CHOICES, default=1)


class Account(models.Model):
    member_id= models.IntegerField()
    account_number= models.IntegerField()
    actual_balance = models.DecimalField(max_digits=10, decimal_places=2)
    available_balance = models.DecimalField(max_digits=10, decimal_places=2)
    account_type = models.IntegerField( choices=ACC_TYPE_CHOICES, default=1)

Transactions/models.py
from django.db import models


TRANSACTION_TYPE_CHOICES = [
        (0, 'Deposit'),
        (1, 'Withdrawal'), 
        (2, 'Loan Repayment'), 
        (3, 'Interest'),  
        (4, 'Fines'),     
    ]

class Transaction(models.Model):
    account_id = models.IntegerField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_reference = models.CharField(max_length=50)
    loan_id = models.IntegerField()
    transaction_type = models.IntegerField( choices=TRANSACTION_TYPE_CHOICES)
    transaction_date = models.DateField()

Members/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from .models import Member 

# Display a list of all students

def member_list(request):
    members = Member.objects.all()
    return render(request, 'member/list.html',{'members':members})


# Display a single student

def member_details(request,id):
    member = Member.objects.get(id=id)

    return render(request, 'member/detail.html',{'member':member})
    

Transactions/views.py
from django.shortcuts import render

# Create your views here.

Members/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
</head>

<body>


        {% block content%}


        {% endblock %}


</body>

</html>

Members/templates/member/detail.html
{% extends "base.html" %}
{%  block title %} Details - {{member.first_name}} {{member.last_name}} {% endblock %}


<div class="container">
    {% block content %}
    <h1> {{member.first_name}} {{member.last_name}}</h1>
    <div class="member-details">
        <p><strong>ID NO</strong> {{member.id_no}}</p>
        <p><strong>First Name:</strong> {{member.first_name}}</p>
        <p><strong>Last Name:</strong> {{member.last_name}}</p>
        <p><strong>Email:</strong> {{member.email}}</p>
        <p><strong>Phone:</strong> {{member.phone_number}}</p>
    </div>
    {% endblock %}
</div>

Members/templates/member/list.html
{% extends "base.html" %}

{%  block title %} All Members {% endblock %}

<div class="container">
{% block content%}
<h2>Members List</h2>
        <table>
            <thead>
                <tr>
                    <th>ID NO</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                </tr>
            </thead>
            <tbody>
               {% for member in members %}
                <tr>
                    <td><a href="{% url 'members:member_details' member.id %}">{{member.id_no}}</a></td>
                    <td>{{member.first_name}}</td>
                    <td>{{member.last_name}}</td>
                    <td>{{member.email}}</td>
                    <td>{{member.phone_number}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


{% endblock %}

</div>